
import { AntivirusProduct, BlogPost } from './types';

export const ANTIVIRUS_PRODUCTS: AntivirusProduct[] = [
  {
    id: 'bitdefender',
    name: 'Bitdefender Antivirus Plus',
    // logo: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Bitdefender_logo.svg',
    // productImage: 'https://m.media-amazon.com/images/I/71-0+wYlWfL.jpg',
    logo:'https://tadenter.com/media/Bitdefender%20Antivirus%20Plus.png',
    productImage:'https://tadenter.com/media/Bitdefender%20Antivirus%20Plus.png',
    rating: 4.9,
    overallScore: 98,
    pros: ['Lightweight performance', 'Excellent malware detection', 'Multi-layer ransomware protection'],
    cons: ['Full scans can be slow', 'Limited iOS features'],
    description: 'Bitdefender consistently tops the charts for its sheer detection capability and minimal impact on system resources in 2026. Its multi-layer ransomware protection and advanced heuristic analysis make it a leader in the security space.',
    pricing: 'Starts at $24.99/year',
    link: 'https://www.bitdefender.com',
    features: ['VPN Included', 'Safepay Banking Protection', 'Password Manager', 'Wi-Fi Security Advisor'],
    performance: { protection: 100, performance: 95, usability: 98 },
    bestFor: 'Best Overall',
    category: 'Premium'
  },
  {
    id: 'norton',
    name: 'Norton 360 Deluxe',
    logo: 'https://bits-mart.com/cdn/shop/files/norton-360-deluxe-3-devices.png?v=1721916565',
    productImage: 'https://bits-mart.com/cdn/shop/files/norton-360-deluxe-3-devices.png?v=1721916565',
    rating: 4.8,
    overallScore: 96,
    pros: ['Dark Web Monitoring', 'Parental Controls', '100% Virus Protection Promise'],
    cons: ['Expensive renewals', 'Interface can feel cluttered'],
    description: 'Norton 360 offers a comprehensive security suite that goes far beyond simple virus scanning. The 2026 edition includes enhanced cloud backup and privacy monitoring tools that are second to none.',
    pricing: 'Starts at $39.99/year',
    link: 'https://www.norton.com',
    features: ['50GB Cloud Backup', 'Privacy Monitor', 'Secure VPN', 'School Time Feature'],
    performance: { protection: 99, performance: 92, usability: 94 },
    bestFor: 'Best for Windows',
    category: 'Windows'
  },
  {
    id: 'eset',
    name: 'ESET HOME Security',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2RhwaAQ8Dna0upNA92oIoih5d6XCxdj4U4Q&s',
    productImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2RhwaAQ8Dna0upNA92oIoih5d6XCxdj4U4Q&s',
    rating: 4.8,
    overallScore: 95,
    pros: ['Extremely light on resources', 'Advanced UEFI & Boot scanning', 'Excellent diagnostics for pros'],
    cons: ['Interface can be complex', 'Basic parental controls'],
    description: 'ESET is the technician\'s choice. In 2026, its NOD32 engine remains the gold standard for low-impact, high-efficiency protection that won\'t slow down your gaming or creative workflows.',
    pricing: 'Starts at $29.99/year',
    link: 'https://www.eset.com',
    features: ['UEFI Scanner', 'Anti-Phishing', 'Gamer Mode', 'Exploit Blocker'],
    performance: { protection: 99, performance: 100, usability: 88 },
    bestFor: 'Best for Performance',
    category: 'Windows'
  },
  {
    id: 'kaspersky',
    name: 'Kaspersky Premium',
    logo: 'https://probazaar.in/wp-content/uploads/2025/05/Kaspersky-Premium-Antivirus-1-Device-for-1-Year-Protection.webp',
    productImage: 'https://probazaar.in/wp-content/uploads/2025/05/Kaspersky-Premium-Antivirus-1-Device-for-1-Year-Protection.webp',
    rating: 4.7,
    overallScore: 95,
    pros: ['Excellent phishing protection', 'Highly intuitive UI', 'Safe Money browser'],
    cons: ['Geopolitical concerns for some users', 'Basic mobile app'],
    description: 'Kaspersky remains a powerhouse in technical security, offering some of the most advanced heuristic analysis in the industry. Its 2026 update provides ultra-fast scanning without system slowdown.',
    pricing: 'Starts at $29.99/year',
    link: 'https://www.kaspersky.com',
    features: ['Real-time Antivirus', 'Online Payment Protection', 'Hard Drive Health Monitor', 'Uninterrupted Gaming Mode'],
    performance: { protection: 100, performance: 98, usability: 96 },
    bestFor: 'Best for Techies',
    category: 'Premium'
  },
  {
    id: 'totalav',
    name: 'TotalAV Antivirus',
    logo: 'https://ms.codes/cdn/shop/articles/totalav-antivirus-pro_153361.png?v=1707845336',
    productImage: 'https://ms.codes/cdn/shop/articles/totalav-antivirus-pro_153361.png?v=1707845336',
    rating: 4.7,
    overallScore: 94,
    pros: ['Very easy to use', 'Great malware detection', 'Comprehensive optimization tools'],
    cons: ['Higher renewal prices', 'VPN only on higher tiers'],
    description: 'TotalAV has quickly risen to the top of the 2026 rankings by focusing on ease of use. It\'s the perfect choice for those who want "set it and forget it" protection combined with system cleanup tools.',
    pricing: 'Starts at $19.00/year',
    link: 'https://www.totalav.com',
    features: ['System Tune-up', 'Real-time Protection', 'Web Shield', 'Ad Block Pro'],
    performance: { protection: 98, performance: 90, usability: 99 },
    bestFor: 'Best for Mac',
    category: 'Mac'
  },
  {
    id: 'avast-free',
    name: 'Avast Free Antivirus',
    logo: 'https://tcedi.com/images/avast/avast-free-antivirus-nitro-update-box-231x300.png',
    productImage: 'https://tcedi.com/images/avast/avast-free-antivirus-nitro-update-box-231x300.png',
    rating: 4.5,
    overallScore: 90,
    pros: ['Zero cost', 'Solid protection engine', 'Wi-Fi network scanner'],
    cons: ['Frequent upsell notifications', 'Heavier on resources than some paid versions'],
    description: 'The world\'s most popular free antivirus for a reason. In 2026, it offers robust protection without a subscription fee, using a shared global threat database for instant security updates.',
    pricing: 'Free Forever',
    link: 'https://www.avast.com',
    features: ['6 Layers of Security', 'Smart Scan', 'Behavior Shield', 'CyberCapture'],
    performance: { protection: 98, performance: 88, usability: 85 },
    bestFor: 'Best Free Option',
    category: 'Free'
  },
  {
    id: 'mcafee',
    name: 'McAfee Total Protection',
    logo: 'https://5.imimg.com/data5/SELLER/Default/2023/2/XD/UQ/PD/162327682/mcafee-total-protection-500x500.png',
    productImage: 'https://5.imimg.com/data5/SELLER/Default/2023/2/XD/UQ/PD/162327682/mcafee-total-protection-500x500.png',
    rating: 4.6,
    overallScore: 92,
    pros: ['Unlimited device coverage', 'Identity Monitoring', 'Fast scans'],
    cons: ['Higher system resource usage', 'Interface lacks depth'],
    description: 'McAfee is the go-to for families with many devices, offering a single 2026 subscription that covers everything from PCs to smartphones, with a heavy focus on personal identity restoration.',
    pricing: 'Starts at $34.99/year',
    link: 'https://www.mcafee.com',
    features: ['Protection Score', 'Identity Theft Coverage', 'File Shredder', 'Firewall'],
    performance: { protection: 97, performance: 85, usability: 90 },
    bestFor: 'Best for Families',
    category: 'Windows'
  },
  {
    id: 'trend-micro',
    name: 'Trend Micro Maximum Security',
    logo: 'https://tadenter.com/media/Trend%20Micro%20Maximum%20Security.png',
    productImage: 'https://tadenter.com/media/Trend%20Micro%20Maximum%20Security.png',
    rating: 4.5,
    overallScore: 91,
    pros: ['Unbeatable web protection', 'Strong privacy features', 'Excellent ransomware blocking'],
    cons: ['Can be aggressive with false positives', 'Lacks some power features'],
    description: 'Trend Micro excels at preventing threats before they even reach your device. In 2026, its Pay Guard and Web Threat Shield provide elite-level browser protection for online shoppers.',
    pricing: 'Starts at $39.95/year',
    link: 'https://www.trendmicro.com',
    features: ['Pay Guard', 'Social Media Privacy', 'Ransom Buster', 'Fraud Buster'],
    performance: { protection: 99, performance: 88, usability: 92 },
    bestFor: 'Best Web Protection',
    category: 'Windows'
  },
  {
    id: 'sophos',
    name: 'Sophos Home Premium',
    logo: 'https://5.imimg.com/data5/SELLER/Default/2021/4/BS/IK/FS/113833305/e-commerce-service.jpg',
    productImage: 'https://5.imimg.com/data5/SELLER/Default/2021/4/BS/IK/FS/113833305/e-commerce-service.jpg',
    rating: 4.4,
    overallScore: 89,
    pros: ['Enterprise-grade protection', 'Remote management console', 'Great for managing family PCs'],
    cons: ['Slow scan times', 'Interface feels "industrial"'],
    description: 'Sophos brings business-level security to the home in 2026. Its unique cloud management dashboard allows you to secure and manage all your family\'s devices from any web browser.',
    pricing: 'Starts at $44.99/year',
    link: 'https://www.sophos.com',
    features: ['Cloud Management', 'Predictive AI', 'Advanced Ransomware Defense', 'Web Filtering'],
    performance: { protection: 100, performance: 82, usability: 85 },
    bestFor: 'Best Remote Management',
    category: 'Mac'
  },
  {
    id: 'malwarebytes',
    name: 'Malwarebytes Premium',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwJL1QBvKsTZ0U3ltBGZcbRuA3evSKY1Y9lw&s',
    productImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwJL1QBvKsTZ0U3ltBGZcbRuA3evSKY1Y9lw&s',
    rating: 4.3,
    overallScore: 88,
    pros: ['Best-in-class remediation', 'Very light footprint', 'Doesn\'t conflict with other AV'],
    cons: ['Missing some traditional AV extras', 'Basic firewall settings'],
    description: 'Malwarebytes 2026 continues its legacy as the ultimate cleanup tool. While it now offers full real-time protection, its strength remains its ability to find and remove deeply nested threats that others miss.',
    pricing: 'Starts at $44.99/year',
    link: 'https://www.malwarebytes.com',
    features: ['Brute Force Protection', 'Real-time Shield', 'Anti-Exploit', 'Quick Scan'],
    performance: { protection: 95, performance: 98, usability: 94 },
    bestFor: 'Best for Cleanup',
    category: 'Premium'
  },
  {
    id: 'avg-free',
    name: 'AVG AntiVirus Free',
    logo: 'https://image.2gosoftware.eu/img/624/624/catalog/AVG-Antivirus.png',
    productImage: 'https://image.2gosoftware.eu/img/624/624/catalog/AVG-Antivirus.png',
    rating: 4.4,
    overallScore: 89,
    pros: ['Fast performance', 'Very customizable', 'Solid protection'],
    cons: ['Shared Avast database (not unique)', 'Heavy upselling'],
    description: 'AVG Free is Avast\'s sibling but offers a different, more traditional interface that many users prefer in 2026. It provides identical core protection with a slightly snappier feel.',
    pricing: 'Free Forever',
    link: 'https://www.avg.com',
    features: ['Email Shield', 'Real-time Updates', 'Web & Email Shield', 'Scans for hidden performance issues'],
    performance: { protection: 98, performance: 92, usability: 88 },
    bestFor: 'Best Free Alternative',
    category: 'Free'
  },
  {
    id: 'avira-free',
    name: 'Avira Free Security',
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8_f5oijwrL6bhjhu9_6iEl5fep8gZCDk18A&s',
    productImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8_f5oijwrL6bhjhu9_6iEl5fep8gZCDk18A&s',
    rating: 4.3,
    overallScore: 87,
    pros: ['Good detection rates', 'Includes basic VPN', 'Privacy-focused'],
    cons: ['Slow full scans', 'UI can be confusing'],
    description: 'Avira is the privacy-conscious choice for 2026. Their free suite includes a basic VPN and a powerful scanning engine that respects user privacy more than most competitors.',
    pricing: 'Free Forever',
    link: 'https://www.avira.com',
    features: ['Phantom VPN', 'Privacy Pal', 'Safe Shopping', 'System Speedup'],
    performance: { protection: 96, performance: 85, usability: 82 },
    bestFor: 'Best Free Privacy AV',
    category: 'Free'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'How to Choose the Best Antivirus Software in 2026',
    excerpt: 'Not all antivirus solutions are created equal. Learn the key factors to look for when securing your digital life in 2026.',
    content: 'Choosing an antivirus is more than just looking at a rating. You need to consider system impact, additional features like VPNs, and the specific threats you face in 2026...',
    date: 'Dec 01, 2025',
    author: 'Tech Expert',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    category: 'Buying Guides'
  },
  {
    id: '2',
    title: 'Antivirus vs. Antimalware: What is the Difference?',
    excerpt: 'Confused by the terminology? We break down the differences between these two essential security layers.',
    content: 'While the terms are often used interchangeably, there are distinct differences in how antivirus and antimalware products function...',
    date: 'Dec 05, 2025',
    author: 'Security Analyst',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800',
    category: 'Education'
  },
  {
    id: '3',
    title: '5 Security Tips for Small Business Owners',
    excerpt: 'Small businesses are prime targets for cyberattacks. Here is how to protect your assets on a budget.',
    content: 'Protecting a small business requires a multi-faceted approach. Start with a solid firewall, implement 2FA, and ensure all endpoints have premium security...',
    date: 'Dec 12, 2025',
    author: 'Business Pro',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    category: 'Business'
  },
  {
    id: '4',
    title: 'Latest Malware Threats: What to Watch Out For',
    excerpt: 'Cybercriminals are getting smarter. Stay ahead of the latest phishing scams and zero-day exploits.',
    content: 'From sophisticated ransomware to AI-driven phishing attacks, the threat landscape is evolving rapidly...',
    date: 'Dec 20, 2025',
    author: 'Threat Hunter',
    image: 'https://intellipaat.com/blog/wp-content/uploads/2025/01/malware-thretas-feature-iamge.jpg',
    category: 'News'
  },
  {
    id: '5',
    title: 'Is Free Antivirus Enough for Home Users?',
    excerpt: 'We analyze whether free software can actually stand up to modern web threats.',
    content: 'Free antivirus tools have improved dramatically, but do they provide enough depth for modern online banking and shopping?',
    date: 'Dec 28, 2025',
    author: 'Home Security',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREqjskf-mfWbnspGkyOquPdo3A4iRpQ54f7A&s',
    category: 'Reviews'
  },
  {
    id: '6',
    title: 'The Rise of Ransomware as a Service',
    excerpt: 'Understanding how the dark web economy is fueling global cybercrime.',
    content: 'Ransomware-as-a-Service (RaaS) has lowered the barrier to entry for cybercriminals...',
    date: 'Jan 02, 2026',
    author: 'Security Lead',
    image: 'https://images.unsplash.com/photo-1562813733-b31f71025d54?auto=format&fit=crop&q=80&w=800',
    category: 'Industry'
  },
  {
    id: '7',
    title: 'Protecting Your Kids Online: A Parent Guide',
    excerpt: 'Practical steps to secure your children\'s devices and educate them on web safety.',
    content: 'Parental controls are a great start, but education is the ultimate firewall...',
    date: 'Jan 08, 2026',
    author: 'Tech Parent',
    image: 'https://images.unsplash.com/photo-1484820540004-14229fe36ca4?auto=format&fit=crop&q=80&w=800',
    category: 'Privacy'
  },
  {
    id: '8',
    title: 'Why You Need a Password Manager Today',
    excerpt: 'Stop using the same password for everything. Here is why a manager is essential.',
    content: 'A password manager is the single most important tool for improving your digital hygiene...',
    date: 'Jan 15, 2026',
    author: 'Privacy Advocate',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
    category: 'Security Tools'
  },
  {
    id: '9',
    title: 'Mac vs. Windows: Which is More Secure?',
    excerpt: 'The age-old debate revisited with 2026 security data.',
    content: 'While Macs were historically seen as immune, the landscape has shifted significantly...',
    date: 'Jan 22, 2026',
    author: 'OS Expert',
    image: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&q=80&w=800',
    category: 'Comparisons'
  },
  {
    id: '10',
    title: 'Securing Your Home IoT Devices',
    excerpt: 'Your smart fridge might be a security risk. Learn how to lock down your network.',
    content: 'Every connected device in your home is a potential entry point for hackers...',
    date: 'Jan 29, 2026',
    author: 'IoT specialist',
    image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&q=80&w=800',
    category: 'Home Tech'
  }
];

export const COMPANY_DETAILS = {
  name: 'TAD Enterprises',
  address: 'Booth No. 4512, R-4/3051, Flat No. A/03, Tirupati Vihar, Papvinash Mandir Road, Near Balaji Mandir, Latur, Maharashtra, 413512',
  website: 'https://tadenter.com/',
  email: 'support@tadenter.com'
};
